# Generated by Django 5.0.14 on 2026-05-27 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='orgs.organization'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['organization'], name='exports_organiz_cdde4c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization'], name='projects_organiz_896a0c_idx'),
        ),
    ]
