# Generated by Django 5.0.14 on 2026-05-27 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_invitation_invites_org_created_idx_and_more'),
        ('projects', '0004_org_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blueprint',
            index=models.Index(fields=['project', '-version'], name='blueprints_project_version_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', '-updated_at'], name='projects_org_updated_idx'),
        ),
    ]
