# Generated by Django 5.0.14 on 2026-05-27 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', '-created_at'], name='invites_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'organization'], name='memberships_user_org_idx'),
        ),
    ]
